# Generated by Django 6.0.4 on 2026-04-20 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='01000000001', help_text='رقم الهاتف: 11 رقم يبدأ بصفر (مثال: 01234567890)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 11 رقم ويبدأ بصفر (مثال: 01234567890)', regex='^0\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional username (phone is used for login)', max_length=150, null=True, unique=True),
        ),
    ]
