# Generated by Django 6.0.4 on 2026-05-09 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent phone number (11 digits starting with 01)', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يتكون من 11 رقماً ويبدأ بـ 01', regex='^01\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, help_text='Student phone number (11 digits starting with 01)', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يتكون من 11 رقماً ويبدأ بـ 01', regex='^01\\d{9}$')]),
        ),
    ]
