# Generated by Django 6.0.4 on 2026-06-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='تاريخ الميلاد', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hall_name',
            field=models.CharField(blank=True, default='', help_text='اسم القاعة / المجموعة', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, help_text='تاريخ الانضمام (يُدخله المشرف)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Nickname or short name (اللقب / الاسم المختصر)', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='ملاحظات إضافية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(help_text="Student's full name", max_length=255, unique=True),
        ),
    ]
