# Generated by Django 6.0.4 on 2026-06-22 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='child_pickup_person',
            field=models.CharField(blank=True, default='', help_text='من يستلم الطفل بعد الانتهاء', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_address',
            field=models.TextField(blank=True, default='', help_text='عنوان السكن'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_calls_phone',
            field=models.CharField(blank=True, help_text='رقم هاتف المكالمات لولي الأمر (11 رقماً يبدأ بـ 01)', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يتكون من 11 رقماً ويبدأ بـ 01', regex='^01\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_full_name',
            field=models.CharField(blank=True, default='', help_text='الاسم الرباعي لولي الأمر', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_job',
            field=models.CharField(blank=True, default='', help_text='الوظيفة الحالية لولي الأمر', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_marital_status',
            field=models.CharField(blank=True, choices=[('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل'), ('separated', 'منفصل')], default='', help_text='الحالة الاجتماعية لولي الأمر', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_qualification',
            field=models.CharField(blank=True, default='', help_text='المؤهل الدراسي لولي الأمر', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_spouse_job',
            field=models.CharField(blank=True, default='', help_text='وظيفة الزوج / الزوجة (إن وُجدت)', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent WhatsApp number (11 digits starting with 01)', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يتكون من 11 رقماً ويبدأ بـ 01', regex='^01\\d{9}$')]),
        ),
    ]
