# Generated by Django 6.0.4 on 2026-07-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_parent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('supervisor', 'Supervisor')], default='teacher', help_text='User role determining access level', max_length=10),
        ),
    ]
