# Generated by Django 6.0.4 on 2026-07-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_supervisor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة الطالب', null=True, upload_to='students/images/%Y/%m/'),
        ),
    ]
