# Generated by Django 6.0.4 on 2026-08-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(blank=True, db_index=True, help_text='كود المعلم', max_length=50, null=True, unique=True),
        ),
    ]
