# Generated by Django 6.0.4 on 2026-08-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teacher_teacher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_course',
            field=models.BooleanField(default=False, help_text='صح إذا كان هذا السجل يمثل كورساً وليس معلماً أساسياً — للتمييز في قائمة محطة المسح فقط'),
        ),
    ]
