# Generated by Django 6.0.4 on 2026-08-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teacher_is_course'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentteacherlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='unique_primary_teacher_per_student'),
        ),
    ]
