# Generated by Django 6.0.4 on 2026-08-14 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_studentteacherlink_unique_primary_teacher_per_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, default='', help_text='وصف الكورس أو ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إلغاء التفعيل بدلاً من الحذف عند وجود سجلات مرتبطة'),
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(help_text='1–12')),
                ('status', models.CharField(choices=[('not_paid', 'لم يُدفع'), ('partial', 'دفع جزئي'), ('paid', 'تم الدفع')], default='not_paid', max_length=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='المبلغ المدفوع فعلياً (اختياري — للتتبع المالي إن وجد)', max_digits=8, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(limit_choices_to={'is_course': True}, on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='core.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='core.student')),
            ],
            options={
                'db_table': 'course_payments',
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'course', 'year', 'month')},
            },
        ),
    ]
