# Generated by Django 6.0.4 on 2026-08-14 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teacher_description_teacher_is_active_coursepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('supervisor', 'Supervisor'), ('assistant', 'Assistant')], default='teacher', help_text='User role determining access level', max_length=10),
        ),
        migrations.CreateModel(
            name='AssistantTeacherLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_links', to='core.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_teacher_links',
                'unique_together': {('user', 'teacher')},
            },
        ),
    ]
