# Generated by Django 6.0.4 on 2026-09-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_role_assistantteacherlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_type',
            field=models.CharField(choices=[('عام', 'عام'), ('أزهر', 'أزهر'), ('لغات', 'لغات'), ('تجريبي', 'تجريبي'), ('غير محدد بعد', 'غير محدد بعد')], default='غير محدد بعد', help_text='نوع التعليم', max_length=20),
        ),
    ]
