# Generated by Django 6.0.4 on 2026-09-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_student_education_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hall_name',
            field=models.CharField(blank=True, default='', help_text='القاعة', max_length=100),
        ),
    ]
