# Generated by Django 6.0.4 on 2026-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('delete', 'حذف'), ('edit', 'تعديل')], max_length=10)),
                ('actor_phone', models.CharField(max_length=20)),
                ('ip_address', models.CharField(max_length=45)),
                ('object_type', models.CharField(max_length=60)),
                ('object_repr', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'سجل المراجعة',
                'verbose_name_plural': 'سجلات المراجعة',
                'ordering': ['-timestamp'],
            },
        ),
    ]
