# Generated by Django 6.0.4 on 2026-04-22 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField()),
                ('substitute_note', models.CharField(blank=True, help_text='Reason/details when assigned teacher differs from original teacher', max_length=255)),
                ('daily_photo', models.ImageField(blank=True, help_text='Optional daily photo captured for the student', null=True, upload_to='attendance/daily_photos/%Y/%m/%d/')),
                ('rating', models.PositiveSmallIntegerField(default=6, help_text='Daily student rating from 1 to 10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, help_text='Teacher assigned for this attendance day (substitute aware)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_student_attendance_records', to='core.teacher')),
                ('original_teacher', models.ForeignKey(blank=True, help_text='Default/original teacher for the student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_student_attendance_records', to='core.teacher')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Admin user who recorded attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_student_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who checked in', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Attendance Record',
                'verbose_name_plural': 'Student Attendance Records',
                'db_table': 'student_attendance_records',
                'ordering': ['-date', '-check_in_time'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_per_day'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 10)), name='student_attendance_rating_range_1_to_10')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Admin user who recorded attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_teacher_attendance', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher who checked in', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Attendance Record',
                'verbose_name_plural': 'Teacher Attendance Records',
                'db_table': 'teacher_attendance_records',
                'ordering': ['-date', '-check_in_time'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date'), name='unique_teacher_attendance_per_day')],
            },
        ),
    ]
