# Generated by Django 6.0.4 on 2026-05-03 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0004_student_student_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendancerecord',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes for this attendance record'),
        ),
        migrations.AddField(
            model_name='teacherattendancerecord',
            name='rating',
            field=models.PositiveSmallIntegerField(default=7, help_text='Daily teacher rating from 1 to 10'),
        ),
        migrations.AddConstraint(
            model_name='teacherattendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 10)), name='teacher_attendance_rating_range_1_to_10'),
        ),
    ]
