# Generated by Django 6.0.4 on 2026-05-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teacher_attendance_rating_and_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendancerecord',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Daily teacher rating from 1 to 10'),
        ),
    ]
