# Generated by Django 6.0.4 on 2026-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_teacherattendancerecord_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendancerecord',
            name='teacher_note',
            field=models.TextField(blank=True, default='', help_text='Teacher note for this attendance record'),
        ),
    ]
