# Generated by Django 6.0.4 on 2026-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_teacher_note_to_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendancerecord',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='Time the teacher left (set on second scan)', null=True),
        ),
    ]
