# Generated by Django 6.0.4 on 2026-06-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_teacher_attendance_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendancerecord',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='Time the student left (set on second scan)', null=True),
        ),
    ]
