# Generated by Django 6.0.4 on 2026-08-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_student_attendance_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendancerecord',
            old_name='daily_photo',
            new_name='homework_photo',
        ),
        migrations.AlterField(
            model_name='studentattendancerecord',
            name='homework_photo',
            field=models.ImageField(blank=True, help_text='صفحة الواجب — Homework page photo', null=True, upload_to='attendance/daily_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='studentattendancerecord',
            name='test_photo',
            field=models.ImageField(blank=True, help_text='صفحة الاختبار — Test page photo', null=True, upload_to='attendance/test_photos/%Y/%m/%d/'),
        ),
    ]
