# Generated by Django 6.0.4 on 2026-08-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_student_attendance_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendancerecord',
            name='record_type',
            field=models.CharField(choices=[('normal', 'حضور عادي'), ('excused_absence', 'غياب بإذن')], default='normal', help_text='نوع السجل', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherattendancerecord',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='Time the teacher checked in (null if excused absence)', null=True),
        ),
    ]
