# Generated by Django 6.0.4 on 2026-08-12 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_studentattendancerecord_daily_photo_and_more'),
        ('core', '0012_teacher_is_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentattendancerecord',
            name='unique_student_attendance_per_day',
        ),
        migrations.AddConstraint(
            model_name='studentattendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'original_teacher'), name='unique_student_attendance_per_day_per_course'),
        ),
        migrations.AddConstraint(
            model_name='studentattendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('original_teacher__isnull', True)), fields=('student', 'date'), name='unique_student_attendance_per_day_no_course'),
        ),
    ]
